// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvzsxnyklitnijlshlnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2enN4bnlrbGl0bmlqbHNobG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4Mjk4NzYsImV4cCI6MjA2MzQwNTg3Nn0.bfpta1UyO_lItHpcYJf8ywk-bxmsaS_6gdRT5ICjaGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);